
spatial_domain:
  nla: -10  # Northernmost latitude
  sla: -60  # Southernmost latitude
  wlo: -78  # Westernmost longitude
  elo: -34  # Easternmost longitude

unify_grid: !!bool FALSE
unify_grid_resolution: 1

# initial_conditions:
#   month: 4
#   year: 2023

shapefiles:
  crcsas: "/data/shapefiles/CRC-SAS.shp"
  
images: 
  crcsas: "./logos/logo-crcsas.png"
  smn: "./logos/logo-smn.png"
  cima: "./logos/logo-cima.png"
  climar: "./logos/logo-climar.png"
  
output_langs: ["en", "es", "pt"]
# output_plots: ["corr", "anom", "det.fcst", "prob.fcst", "uncal.fcst", 
#                "b20.fcst", "b33.fcst", "a66.fcst", "a80.fcst", 
#                "dry.fcst", "wet.fcst","hot.fcst","cold.fcst"]
output_plots: ["prob.fcst", 
               "b20.fcst", "b33.fcst", "a66.fcst", "a80.fcst",
               "dry.fcst", "wet.fcst","hot.fcst","cold.fcst"] 
output_leadtimes: [1, 2, 3, 4, 5, 6, 7]
output_trgt_type: ["trimesters"]  # ["trimesters", "months"]

pycpt:  
  variables: ["prcp", "t2m"]
  modelos: ["ecmwf", "nmme"]  # ["ecmwf", "nmme", "nasa"]
  fuentes: ["chirps", "era5-land"]  # ["chirps", "era5-land", "crcsas"]
  input_folders:
    observed_data: "/data/pycpt/input/predictands"
    uncalibrated_data: "/data/pycpt/input/predictors"
    calibrated_data: 
      forecasts: "/data/pycpt/output"
      hindcasts: "/data/pycpt/output"
  correction_strategies:
    calibrated_data:
      det_values:
        forecasts: 
          prcp: "cpt_invalid_prcp_values"
        hindcasts: 
          prcp: "cpt_invalid_prcp_values"
  output_folder:
    crcsas: "/data/pycpt/plots/web-crc-sas"
    sissa: "/data/pycpt/plots/web-sissa"
  suavizar_graficos: !!bool TRUE

ereg:  
  variables: ["prec", "tref"]
  modelos:  ["mme"]
  input_folders:
    observed_data: "/data/ereg/generados/nmme_output"
    uncalibrated_data: null
    calibrated_data: 
      forecasts: "/data/ereg/generados/nmme_output/rt_forecasts"
      hindcasts: "/data/ereg/generados/nmme_output/comb_forecasts"
  output_folder: 
    crcsas: "/data/ereg/generados/nmme_figuras/web-crc-sas"
    sissa: "/data/ereg/generados/nmme_figuras/web-sissa"
  suavizar_graficos: !!bool TRUE
  dry_mask_file: "/data/ereg/generados/nmme_output/dry_mask.nc"
  apply_dry_mask: !!bool TRUE
