
spatial_domain:
  nla: -10  # Northernmost latitude
  sla: -60  # Southernmost latitude
  wlo: -78  # Westernmost longitude
  elo: -34  # Easternmost longitude

unify_grid: FALSE
unify_grid_resolution: 1

initial_conditions:
  month: 5
  year: 2022

shapefiles:
  crc-sas: "/data/shapefiles/CRC_SAS.shp"
  
images: 
  crc-sas: "/data/images/logo-crcsas.png"

output_langs: ["en", "es", "pt"]
output_plots: ["prob.fcst"]  # ["corr", "anom", "det.fcst", "prob.fcst", "uncal.fcst"]
output_leadtimes: [1]  # [1, 2, 3, 4, 5, 6, 7]
output_trgt_type: ["trimesters"]  # ["trimesters", "months"]

acc-cpt:  
  variables: ["prcp", "t2m"]
  modelos: ["ecmwf", "nmme", "nasa"]
  fuentes: ["chirps", "era5-land", "crcsas"]
  input_folders:
    observed_data: "/data/acc-cpt/input/predictands"
    uncalibrated_data: "/data/acc-cpt/input/predictors"
    calibrated_data: 
      forecasts: "/data/acc-cpt/output"
      hindcasts: "/data/acc-cpt/output"
  correction_strategies:
    calibrated_data:
      det_values:
        forecasts: 
          prcp: "cpt_invalid_prcp_values"
        hindcasts: 
          prcp: "cpt_invalid_prcp_values"
  output_folder: "/data/acc-cpt/plots/web-crc-sas"
  suavizar_graficos: TRUE

ereg:  
  variables: ["prec", "tref"]
  modelos:  ["mme"]
  input_folders:
    observed_data: "/data/ereg/generados/nmme_output"
    uncalibrated_data: null
    calibrated_data: 
      forecasts: "/data/ereg/generados/nmme_output/rt_forecasts"
      hindcasts: "/data/ereg/generados/nmme_output/comb_forecasts"
  output_folder: "/data/ereg/generados/nmme_figuras/web-crc-sas"
  suavizar_graficos: TRUE
  dry_mask_file: "/data/ereg/descargas/NMME/dry_mask.nc"
  apply_dry_mask: TRUE
